version: '3.9'

services:
  app:
    build:
      context: ./app
    container_name: app_container
    networks:
      - db_network
      - site_network
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4743/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ./app/src/.env

  mysql:
    build:
      context: ./mysql
    container_name: mysql_container
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p"]
      interval: 10s
      timeout: 5s
      retries: 3
    env_file:
      - ./mysql/.env

  nginx:
    build:
      context: ./nginx
    container_name: nginx_container
    networks:
      - site_network
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "5423:5423" 

volumes:
  db_volume:

networks:
  db_network:
  site_network:
